import { supabase } from './supabase';

/**
 * The finished scorecard, stored so the marketing message can attach the same
 * image the student saw on screen.
 *
 * The bucket is public. WhatsApp fetches the image by URL from its own
 * servers and cannot present a token, so a signed link would not work — and
 * the filename is the play code, which is unguessable, exactly as the answers
 * page already is.
 */
const BUCKET = 'scorecards';

/**
 * The play's own code, which is already unique, already generated by the
 * database and already in the sheet as the answers link. Reusing it as the
 * filename means the image's address can be derived from the code alone, so
 * there is nothing new to store and no column that could fall out of step
 * with the file.
 *
 * The .jpg is mirrored in sheets/refresh-leads.gs, which builds the same URL
 * from the other end. Change one and change the other.
 */
function cardPath(code: string): string {
  return `${code}.jpg`;
}

function isAlreadyThere(error: unknown): boolean {
  const status = (error as { statusCode?: string | number })?.statusCode;
  if (String(status) === '409') return true;
  const message = (error as { message?: string })?.message ?? '';
  return /already exists/i.test(message);
}

/**
 * Only a student's first finished round needs a card: the card exists for
 * the WhatsApp message, and each student is messaged once, about that round.
 * The bucket refuses any other round's card anyway
 * (supabase/migration-first-round-cards.sql); asking first just saves a
 * replay from sending a 100 KB image to be turned away.
 *
 * If the question itself fails, the upload goes ahead and the bucket decides.
 */
async function isFirstRound(code: string): Promise<boolean> {
  if (!supabase) return false;
  const { data, error } = await supabase.rpc('play_code_is_first', { p_code: code });
  if (error) return true;
  return data === true;
}

/**
 * Uploads the card if this is the student's first round, quietly.
 *
 * Nothing about this is worth showing the student: they have their score, and
 * a card that failed to upload only means the message they get later carries
 * no image. So every path returns rather than throws, and the caller ignores
 * the result. One retry, because the common failure here is a phone dropping
 * off the network for a moment on the walk out of a lecture hall.
 */
export async function uploadScorecard(code: string, blob: Blob): Promise<boolean> {
  if (!supabase) return false;
  if (!(await isFirstRound(code))) return false;

  const path = cardPath(code);

  for (let attempt = 1; attempt <= 2; attempt++) {
    const { error } = await supabase.storage.from(BUCKET).upload(path, blob, {
      contentType: 'image/jpeg',
      // A year: the file never changes, and WhatsApp may fetch it more than
      // once if the message is retried.
      cacheControl: '31536000',
      // Deliberately off. Each round has its own code, so a collision means
      // this card is already uploaded, not that it needs replacing — and
      // leaving upsert off is what stops a stranger overwriting a card.
      upsert: false,
    });

    if (!error) return true;
    if (isAlreadyThere(error)) return true;
    if (attempt === 1) await new Promise((resolve) => window.setTimeout(resolve, 1500));
  }

  return false;
}
